name: ada
channels:
  - defaults
  - conda-forge
dependencies:
  - nb_conda_kernels
  - ipykernel
  - pandas
  - beautifulsoup4
  - ca-certificates
  - certifi
  - openssl
  - statsmodels
  - scikit-learn
  - nltk
  - transformers
  - kaleido
  - pyldavis
  - pip:
    - syllables
    - ddg3
